export const ROUTES = {
  TEACHER_DASHBOARD: '/teacher/dashboard',
  TEACHER_GROUPS: '/teacher/groups',
  TEACHER_GROUP: (id: string) => `/teacher/groups/${id}`,
  TEACHER_LESSON_CREATE: '/teacher/lessons/create',
  TEACHER_ATTENDANCE: (id: string) => `/teacher/lessons/${id}/attendance`,
  TEACHER_GRADES: (id: string) => `/teacher/lessons/${id}/grades`,
  TEACHER_MATERIAL: '/teacher/materials/add',
  TEACHER_JOURNAL: '/teacher/journal',
  TEACHER_ATTENDANCE_HOME: '/teacher/attendance-home',
  TEACHER_GRADES_HOME: '/teacher/grades-home',
  TEACHER_REPORTS: '/teacher/reports',
  TEACHER_PROFILE: '/teacher/profile',
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_GROUPS: '/student/groups',
  STUDENT_ATTENDANCE: '/student/attendance',
  STUDENT_GRADES: '/student/grades',
  STUDENT_MATERIALS: '/student/materials',
  STUDENT_PROFILE: '/student/profile',
} as const;
